### ISSUE TITLE
Watching same directory multiple times

### ISSUE THREAD

**Issue by davidbrochart** [samuelcolvin/watchfiles#128]
I get strange behaviors when watching the same directory multiple times:
```py
import asyncio
from watchfiles import awatch

async def observe_changes():
    async for _ in awatch("."):
        print("Change detected")

async def main():
    asyncio.create_task(observe_changes())
    asyncio.create_task(observe_changes())
    await asyncio.Future()

asyncio.run(main())
```
In particular, exiting this script by pressing Ctrl-C twice generates the following error:
```
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
FATAL: exception not rethrown
Aborted (core dumped)
```

**Comment by samuelcolvin** [comment]
Please include OS In issues.

Please add `debug=True` and see if you see anything interesting.

**Comment by samuelcolvin** [comment]
You might also get something useful from `RUST_BACKTRACE=1`.

**Comment by davidbrochart** [comment]
OS: Ubuntu 22.04
With `RUST_BACKTRACE=1` and `debug=True`:
```
watcher: INotifyWatcher { channel: Sender { .. }, waker: Waker { inner: Waker { fd: File { fd: 9, path: "anon_inode:[eventfd]", read: true, write: true } } } }
watcher: INotifyWatcher { channel: Sender { .. }, waker: Waker { inner: Waker { fd: File { fd: 12, path: "anon_inode:[eventfd]", read: true, write: true } } } }
^CTraceback (most recent call last):
  File "/home/david/github/davidbrochart/jupyterlab/foo.py", line 13, in <module>
    asyncio.run(main())
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/asyncio/base_events.py", line 1881, in _run_once
    handle._run()
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/david/github/davidbrochart/jupyterlab/foo.py", line 5, in observe_changes
    async for _ in awatch(".", debug=True):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/site-packages/watchfiles/main.py", line 225, in awatch
    raise KeyboardInterrupt
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/threading.py", line 1560, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
FATAL: exception not rethrown
Aborted (core dumped)
```

**Comment by justvanrossum** [comment]
FWIF: I'm seeing the same error in `lock.acquire()` when pressing Ctrl-C twice, when watching two folders, on macOS 10.15.7.

And I'm afraid I also don't see how #132 would fix that.

**Comment by samuelcolvin** [comment]
have you tried the example in #132?

**Comment by justvanrossum** [comment]
Ah, now I understand the example. (But sorry, I didn't try, and I'm not able to right now, soonest tomorrow).

I'm curious whether `awatch()` could by default get the correct `SIGINT` behavior, so user code won't have to deal with an explicit stop event.

**Comment by samuelcolvin** [comment]
> I'm curious whether `awatch()` could by default get the correct `SIGINT` behavior, so user code won't have to deal with an explicit stop event.

Honestly I'm not sure signals are hard. Happy to accept a PR if you can make it work, either way adding the `exit_on_signal` option is not a bad thing.
