### ISSUE TITLE
Watchfiles not detecting changes

### ISSUE THREAD

**Issue by davidbrochart** [samuelcolvin/watchfiles#129]
OS: Ubuntu 22.04
With some code similar to #128, watchfiles doesn't detect changes, although it prints with `debug=True`:
```
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

**Comment by samuelcolvin** [comment]
I'm away from my linux machine at pycon right now, so can't reproduce.

In theory we should catch `Modify(Data(Any))` here:

https://github.com/samuelcolvin/watchfiles/blob/7b41a2350a4d9719dbe8ca5a529336dca94f1a8c/src/lib.rs#L63

But then only register the change if that file has **not** been added or deleted in the same batch.

Are you not seeing changes to that file at all, or just not seeing the modified as well as added/deleted?

**Comment by davidbrochart** [comment]
The file change is not detected when there are two watchers, for two files in the same directory. In this case I see after changing the file:
```
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```
When there is only one file being watched, the file change is detected and I see:
```
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/david/github/davidbrochart/jupyterlab/untitled.txt"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```
It looks like when the file change is detected there are twice the same sequence of events?

**Comment by samuelcolvin** [comment]
I'm a bit confused. In summary: is the problem related to two watchers, or the event types?

Really, you shouldn't be watching the same directory twice with the same process.

It might be worth asking notify whether the OS only notifies a process once about an fs event - that could be causing the problems and would be impossible for watchfiles to fix.

**Comment by davidbrochart** [comment]
The problem is related to two watchers.
Having only one watcher could be a solution indeed, I'll report back how it goes.

**Comment by davidbrochart** [comment]
I still have issues even with one watcher. Most of the time, I get the same behavior as above, i.e. events are reported with `debug=True` but watchfiles doesn't detect them. Sometimes, it starts working, but then subsequent changes are not detected.
I also get this error on exit:
```python-traceback
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<watch_root_directory() done, defined at /home/david/github/davidbrochart/jupyterlab/jupyterlab/handlers/yjs_echo_ws.py:62> exception=TypeError("descriptor 'get_coro' for '_asyncio.Task' objects doesn't apply to a 'Task' object")>
Traceback (most recent call last):
  File "/home/david/github/davidbrochart/jupyterlab/jupyterlab/handlers/yjs_echo_ws.py", line 63, in watch_root_directory
    async for changes in awatch(".", debug=True):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/site-packages/watchfiles/main.py", line 214, in awatch
    tg.cancel_scope.cancel()
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 405, in cancel
    self._deliver_cancellation()
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 361, in _deliver_cancellation
    if task is not current and (task is self._host_task or _task_started(task)):
  File "/home/david/mambaforge/envs/jupyterlab-dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 186, in _task_started
    coro = get_coro(task)
TypeError: descriptor 'get_coro' for '_asyncio.Task' objects doesn't apply to a 'Task' object
```
The watcher (`async for changes in awatch(".", debug=True)`) is running in a task, is that a problem?

**Comment by samuelcolvin** [comment]
Afraid I can't really help without seeing the code.

You'll need to investigate yourself.

**Comment by davidbrochart** [comment]
I understand. Unfortunately I was not able to create a MRE, and it's happening in JupyterLab. If you're willing to investigate with me, I can help you set up an environment. Here is the branch:
https://github.com/davidbrochart/jupyterlab/tree/watchfiles

**Comment by samuelcolvin** [comment]
Is this fixed by the recently released changes?

**Comment by davidbrochart** [comment]
It looks like it's fixed, but I would need test it more in depth.

**Comment by graingert** [comment]
> TypeError: descriptor 'get_coro' for '_asyncio.Task' objects doesn't apply to a 'Task' object

Looks like anyio got imported after nest-asyncio
