### ISSUE TITLE
Permission denied despite using `ignore_paths`

### ISSUE THREAD

**Issue by JeppeKlitgaard** [samuelcolvin/watchfiles#147]
### Description

I have a subdirectory that results in a permission denied error:

```
Traceback (most recent call last):
  File "/home/jeppe/Code/jeppe.science/.venv/bin/watchfiles", line 8, in <module>
    sys.exit(cli())
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/cli.py", line 136, in cli
    run_process(
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/run.py", line 126, in run_process
    for changes in watch(
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/main.py", line 103, in watch
    watcher = RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms)
FileNotFoundError: Permission denied (os error 13) about ["/home/jeppe/Code/jeppe.science/var/pictures"]
```

In order to get around this, I would like to ignore the the folder `var`:
```sh
watchfiles --ignore-paths var "jupytext --sync ./**/*.ipynb" .
```

But this still results in the error above, which is not the behaviour I would expect.

Additionally it would be nice to have another config flag along the lines of `ignore-errors`.

### Example Code

Create a subfolder without read permission.

Then run `watchfiles` on it with `--ignore-paths` on that folder.

### Example Code Output

```Text
Traceback (most recent call last):
  File "/home/jeppe/Code/jeppe.science/.venv/bin/jupytext", line 5, in <module>
    from jupytext.cli import jupytext
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/jupytext/__init__.py", line 3, in <module>
    from .formats import NOTEBOOK_EXTENSIONS, get_format_implementation, guess_format
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/jupytext/formats.py", line 10, in <module>
    import nbformat
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/nbformat/__init__.py", line 9, in <module>
    from traitlets.log import get_logger
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/traitlets/log.py", line 6, in <module>
    import logging
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
KeyboardInterrupt
[12:53:25] process stopped
Traceback (most recent call last):
  File "/home/jeppe/Code/jeppe.science/.venv/bin/watchfiles", line 8, in <module>
    sys.exit(cli())
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/cli.py", line 136, in cli
    run_process(
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/run.py", line 126, in run_process
    for changes in watch(
  File "/home/jeppe/Code/jeppe.science/.venv/lib/python3.10/site-packages/watchfiles/main.py", line 103, in watch
    watcher = RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms)
FileNotFoundError: Permission denied (os error 13) about ["/home/jeppe/Code/jeppe.science/var/pictures"]
```
```


### Operating System

Linux

### Environment

WSL

### Watchfiles Version

0.14.1

### Python Version

3.10

**Comment by JeppeKlitgaard** [comment]
I'd be happy to try and submit a PR for this, if there is appetite for that.

**Comment by samuelcolvin** [comment]
Sorry not to reply earlier.

I don't think this can be fixed in watchfiles since notify (and indeed the OS filesystem watchers) watch an entire directory tree recursively, watchfiles just ignores some notifications.

Non-recursive watching as implemented in #183 might help you.

**Comment by Kludex** [comment]
Can we ignore files that the user doesn't have permissions or this is not a good idea?

I have the same issue on `uvicorn`.

```bash
Running development server on 0.0.0.0:8000
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [7] using WatchFiles
Traceback (most recent call last):
  File "/opt/app-env/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/opt/app-env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/app-env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/app-env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/app-env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/app-env/lib/python3.8/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/opt/app-env/lib/python3.8/site-packages/uvicorn/main.py", line 571, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "/opt/app-env/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 45, in run
    for changes in self:
  File "/opt/app-env/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 64, in __next__
    return self.should_restart()
  File "/opt/app-env/lib/python3.8/site-packages/uvicorn/supervisors/watchfilesreload.py", line 85, in should_restart
    changes = next(self.watcher)
  File "/opt/app-env/lib/python3.8/site-packages/watchfiles/main.py", line 119, in watch
    with RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms, recursive) as watcher:
FileNotFoundError: Permission denied (os error 13) about ["/app/fakenamehere"]
```

**Comment by samuelcolvin** [comment]
Ok, happy to accept a PR to add an option to ignore these errors, should default to error but we can have a env var to change the behaviour.

We should also raise the correct `PermissionError` if we're raising errors.

Related to #208 where I tried to use better errors.
