### ISSUE TITLE
Failed to build on raspberry pi

### ISSUE THREAD

**Issue by bellini666** [samuelcolvin/watchfiles#149]
### Description

`pip install watchfiles` will fail on raspberry pi (watchgod used to work due to it not having a dependency on rust for build)

### Example Code Output

```Text
May 27 15:52:08 raspberrypi nomad[32075]: Building wheels for collected packages: watchfiles
May 27 15:52:08 raspberrypi nomad[32075]:   Building wheel for watchfiles (pyproject.toml): started
May 27 15:52:19 raspberrypi nomad[32075]:   Building wheel for watchfiles (pyproject.toml): finished with status 'error'
May 27 15:52:19 raspberrypi nomad[32075]:   error: subprocess-exited-with-error
May 27 15:52:19 raspberrypi nomad[32075]:   
May 27 15:52:19 raspberrypi nomad[32075]:   × Building wheel for watchfiles (pyproject.toml) did not run successfully.
May 27 15:52:19 raspberrypi nomad[32075]:   │ exit code: 1
May 27 15:52:19 raspberrypi nomad[32075]:   ╰─> [86 lines of output]
May 27 15:52:19 raspberrypi nomad[32075]:       running bdist_wheel
May 27 15:52:19 raspberrypi nomad[32075]:       running build
May 27 15:52:19 raspberrypi nomad[32075]:       running build_py
May 27 15:52:19 raspberrypi nomad[32075]:       creating build
May 27 15:52:19 raspberrypi nomad[32075]:       creating build/lib.linux-armv7l-cpython-39
May 27 15:52:19 raspberrypi nomad[32075]:       creating build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/main.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/__main__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/__init__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/cli.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/version.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/filters.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/run.py -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/py.typed -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       copying watchfiles/_rust_notify.pyi -> build/lib.linux-armv7l-cpython-39/watchfiles
May 27 15:52:19 raspberrypi nomad[32075]:       running build_ext
May 27 15:52:19 raspberrypi nomad[32075]:       running build_rust
May 27 15:52:19 raspberrypi nomad[32075]:       error: failed to parse manifest at `/tmp/pip-install-oq7n_5e8/watchfiles_18ef0f38700145e2ac1d399d2fe24acf/Cargo.toml`
May 27 15:52:19 raspberrypi nomad[32075]:       
May 27 15:52:19 raspberrypi nomad[32075]:       Caused by:
May 27 15:52:19 raspberrypi nomad[32075]:         failed to parse the `edition` key
May 27 15:52:19 raspberrypi nomad[32075]:       
May 27 15:52:19 raspberrypi nomad[32075]:       Caused by:
May 27 15:52:19 raspberrypi nomad[32075]:         supported edition values are `2015` or `2018`, but `2021` is unknown
May 27 15:52:19 raspberrypi nomad[32075]:       Traceback (most recent call last):
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
May 27 15:52:19 raspberrypi nomad[32075]:           main()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
May 27 15:52:19 raspberrypi nomad[32075]:           json_out['return_val'] = hook(**hook_input['kwargs'])
May 27 15:52:19 raspberrypi nomad[32075]:         File "/home/pi/nomad/.nomad_venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
May 27 15:52:19 raspberrypi nomad[32075]:           return _build_backend().build_wheel(wheel_directory, config_settings,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
May 27 15:52:19 raspberrypi nomad[32075]:           return self._build_with_temp_dir(['bdist_wheel'], '.whl',
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_setup()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
May 27 15:52:19 raspberrypi nomad[32075]:           super(_BuildMetaLegacyBackend,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
May 27 15:52:19 raspberrypi nomad[32075]:           exec(compile(code, __file__, 'exec'), locals())
May 27 15:52:19 raspberrypi nomad[32075]:         File "setup.py", line 23, in <module>
May 27 15:52:19 raspberrypi nomad[32075]:           setup(
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
May 27 15:52:19 raspberrypi nomad[32075]:           return distutils.core.setup(**attrs)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
May 27 15:52:19 raspberrypi nomad[32075]:           return run_commands(dist)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
May 27 15:52:19 raspberrypi nomad[32075]:           dist.run_commands()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command(cmd)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command('build')
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           self.distribution.run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_command(cmd_name)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           self.distribution.run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1229, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           super().run_command(command)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
May 27 15:52:19 raspberrypi nomad[32075]:           cmd_obj.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/setuptools_ext.py", line 124, in run
May 27 15:52:19 raspberrypi nomad[32075]:           build_rust.run()
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/command.py", line 101, in run
May 27 15:52:19 raspberrypi nomad[32075]:           self.run_for_extension(ext)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 112, in run_for_extension
May 27 15:52:19 raspberrypi nomad[32075]:           dylib_paths = self.build_extension(ext, self.target)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 143, in build_extension
May 27 15:52:19 raspberrypi nomad[32075]:           target_dir = _base_cargo_target_dir(ext)
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 690, in _base_cargo_target_dir
May 27 15:52:19 raspberrypi nomad[32075]:           target_directory = ext._metadata()["target_directory"]
May 27 15:52:19 raspberrypi nomad[32075]:         File "/tmp/pip-build-env-88hys80r/overlay/lib/python3.9/site-packages/setuptools_rust/extension.py", line 225, in _metadata
May 27 15:52:19 raspberrypi nomad[32075]:           self._cargo_metadata = json.loads(subprocess.check_output(metadata_command))
May 27 15:52:19 raspberrypi nomad[32075]:         File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
May 27 15:52:19 raspberrypi nomad[32075]:           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
May 27 15:52:19 raspberrypi nomad[32075]:         File "/usr/lib/python3.9/subprocess.py", line 528, in run
May 27 15:52:19 raspberrypi nomad[32075]:           raise CalledProcessError(retcode, process.args,
May 27 15:52:19 raspberrypi nomad[32075]:       subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.
May 27 15:52:19 raspberrypi nomad[32075]:       [end of output]
May 27 15:52:19 raspberrypi nomad[32075]:   
May 27 15:52:19 raspberrypi nomad[32075]:   note: This error originates from a subprocess, and is likely not a problem with pip.
May 27 15:52:19 raspberrypi nomad[32075]:   ERROR: Failed building wheel for watchfiles
May 27 15:52:19 raspberrypi nomad[32075]: Failed to build watchfiles
```

### Operating System

Raspbian

### Watchfiles Version

none

### Python Version

3.9

**Comment by samuelcolvin** [comment]
Should work if you first install rust.

Is there an example of another package that distributed manylinux binaries which do work on a pi? If so we can probably copy that package and provide binaries fairly easily.

**Comment by bellini666** [comment]
> Should work if you first install rust.

That issue is after installing `rustc`

> Is there an example of another package that distributed manylinux binaries which do work on a pi? If so we can probably copy that package and provide binaries fairly easily.

Hrmm, don't really know. Will try to find one!

**Comment by samuelcolvin** [comment]
You need cargo installed as well, see https://github.com/samuelcolvin/watchfiles/issues/142#issuecomment-1127685787

**Comment by bellini666** [comment]
> You need cargo installed as well, see [#142 (comment)](https://github.com/samuelcolvin/watchfiles/issues/142#issuecomment-1127685787)

`apt install rustc` installs cargo as well. you can see in the logs that cargo got executed correctly, it just failed to parse something in the `Cargo.toml` file

**Comment by samuelcolvin** [comment]
Looks like apt is installing an ancient version of cargo. Install with rustup.

**Comment by bellini666** [comment]
> Looks like apt is installing an ancient version of cargo. Install with rustup.

This is the default version in debian buster. It is a production server in which we cannot use `rustup`.

Is newer versions of cargo required to run this project? If so, which is the minimum version?

**Comment by samuelcolvin** [comment]
Well we have edition 2021 in Cargo.toml which I think requires 1.56 or 1.57 (in on my phone, so haven't checked).

That's the only requirement I know if, if you lower edition, I don't know what version could be supported.

**Comment by samuelcolvin** [comment]
Which raspberry pi are you on? It [looks](https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/) like all recent pis are arm64, which we pypi includes binaries for.

Are you sure you're not using a very old version of pip or something?

**Comment by bellini666** [comment]
It's a mix of raspberry 3 model B and B+ in close to a hundred machines.

**Comment by samuelcolvin** [comment]
Then the binaries from pypi should work fine.

Dumb question, but have you tried just

```bash
pip install -U pip
pip install watchfiles
```

?

**Comment by bellini666** [comment]
Wheels from rpi usually come from piwheels (https://www.piwheels.org/). If they are not there, pip will download the `.tar.gz` archive and build it locally.

watchgod for example has a successful build for both buster and bullseye for version 0.8.1 there: https://www.piwheels.org/project/watchgod/

watchfiles failed to build there: https://www.piwheels.org/project/watchfiles/ . You can even check the build logs, they are the same as mine: https://www.piwheels.org/logs/0000/0825/2816.txt

> Dumb question, but have you tried just

Yes :)

**Comment by samuelcolvin** [comment]
Ok, can you try downloading the appropriate wheel from pypi and installing it with `pip install <filename>`, and let me know what happens.

**Comment by samuelcolvin** [comment]
Sorry, I don't have a RPI where I am for the next 2 months, or I'd try myself.

**Comment by bellini666** [comment]
Np, I'm glad to try here.

But AFAIK there's no available wheel for the rpi arch (it is a `armhf`/`ARMv7`)

**Comment by prcutler** [comment]
I saw the question on Twitter and tested it - it would not build for me on a Raspberry Pi Zero 2 W.

Here is the output when I ran:
```
pip install -U pip
pip install watchfiles
```

```
pip install -U pip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-22.1.1-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 8.9 kB/s
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.9 are installed in '/home/prcutler/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.1.1
prcutler@pizero:~/workspace $ pip install watchfiles
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting watchfiles
  Downloading watchfiles-0.14.1.tar.gz (18 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for watchfiles from https://files.pythonhosted.org/packages/c7/ff/dace40df6b334bf1bf0a3d56273e5ea08a590d9d342c63f54e6cb014cdf6/watchfiles-0.14.1.tar.gz#sha256=babcc3a3502879224e33ba5f25adfbf37a4f22898977c2d96d0ed3eee99eca8a.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting anyio<4,>=3.0.0
  Downloading https://www.piwheels.org/simple/anyio/anyio-3.6.1-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 294.6 kB/s eta 0:00:00
Collecting sniffio>=1.1
  Downloading https://www.piwheels.org/simple/sniffio/sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<4,>=3.0.0->watchfiles) (2.10)
Building wheels for collected packages: watchfiles
  Building wheel for watchfiles (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for watchfiles (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-39
      creating build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/run.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/__init__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/version.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/main.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/cli.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/__main__.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/filters.py -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/py.typed -> build/lib.linux-armv7l-cpython-39/watchfiles
      copying watchfiles/_rust_notify.pyi -> build/lib.linux-armv7l-cpython-39/watchfiles
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for watchfiles
Failed to build watchfiles
ERROR: Could not build wheels for watchfiles, which is required to install pyproject.toml-based projects
```

**Comment by samuelcolvin** [comment]
Thanks @prcutler for confirming, this is the same error as above because:
1. piwheels doesn't have binaries for watchfiles
2. You don't have rust and cargo installed

@bellini666, worth trying the arm64 binaries from pypi, just to see what happens.

**Comment by ryancheley** [comment]
@samuelcolvin I tested it on my Raspberry Pi 3 and this is what I get

```

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting watchfiles
  Downloading watchfiles-0.14.1.tar.gz (18 kB)
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for watchfiles from https://files.pythonhosted.org/packages/c7/ff/dace40df6b334bf1bf0a3d56273e5ea08a590d9d342c63f54e6cb014cdf6/watchfiles-0.14.1.tar.gz#sha256=babcc3a3502879224e33ba5f25adfbf37a4f22898977c2d96d0ed3eee99eca8a.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting anyio<4,>=3.0.0
  Downloading https://www.piwheels.org/simple/anyio/anyio-3.6.1-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 334.2 kB/s eta 0:00:00
Collecting idna>=2.8
  Downloading https://www.piwheels.org/simple/idna/idna-3.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 262.5 kB/s eta 0:00:00
Collecting sniffio>=1.1
  Downloading https://www.piwheels.org/simple/sniffio/sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting typing-extensions
  Using cached https://www.piwheels.org/simple/typing-extensions/typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Building wheels for collected packages: watchfiles
  Building wheel for watchfiles (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for watchfiles (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-cpython-37
      creating build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/filters.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/__init__.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/__main__.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/version.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/cli.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/main.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/run.py -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/py.typed -> build/lib.linux-armv7l-cpython-37/watchfiles
      copying watchfiles/_rust_notify.pyi -> build/lib.linux-armv7l-cpython-37/watchfiles
      running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for watchfiles
Failed to build watchfiles
ERROR: Could not build wheels for watchfiles, which is required to install pyproject.toml-based projects

```

**Comment by samuelcolvin** [comment]
Thanks, yes see above, this is the same error others have got.

**Comment by bellini666** [comment]
@ryancheley your error there is that you don't have rust compiler installed. `apt install rustc cargo` should fix that issue, then you will run into mine: `supported edition values are `2015` or `2018`, but `2021` is unknown`

@samuelcolvin pip won't allow me to install the arm64 wheel (and it shouldn't, the arch is not the same):

```
$ pip install watchfiles-0.14.1-cp39-cp39-macosx_11_0_arm64.whl 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: watchfiles-0.14.1-cp39-cp39-macosx_11_0_arm64.whl is not a supported wheel on this platform.
```

**Comment by samuelcolvin** [comment]
Or you can install rust stable with rustup and it should work fine.

**Comment by bellini666** [comment]
> Or you can install rust stable with rustup and it should work fine.

This is not an option for me unfortunately, and probably won't be for many too

**Comment by bellini666** [comment]
Also it is worth noting that the lack of a wheel for raspberry pi and the fact that it needs to compile the rust extension might be a deal breaker for many, since the installation process takes too long. I had similar cases where the compilation of a package took close to 10 minutes on the pi (and that on a rpi 3. the rpi zero could take even more).

I unfortunately had to downgrade the use of this lib and go back to `watchgod` for now since it installs and works fine. I would really want to upgrade to the improved `watchfiles` in the future though

**Comment by samuelcolvin** [comment]
> This is not an option for me unfortunately, and probably won't be for many too

Yes you said, but if someone else could try this and confirm if watchfiles is working, it would help a lot.

---

My best is guess that the piwheels build is failing because it too is using rustc/cargo from apt which is old. Hopefully if we could modify watchfiles to support older rustc/cargo, the piwheel build might work and install for others on pis should work easily.

Questions:
1. What version of rustc and cargo is apt installing?
2. (Probably for the piwheels maintainers) is there a way to test Piwheels builds?

(I haven't yet had a chance to review the piwheels build log on a laptop, that might tell us a lot).

**Comment by jack1142** [comment]
> This is the default version in debian buster. It is a production server in which we cannot use rustup.

Do you have to use armhf system though? Raspberry Pi OS supports aarch64 now and there's other systems like Ubuntu which also support aarch64 and provide pre-installed images for Pis. Or you could move onto armhf Raspberry Pi OS 11 (bullseye) which probably has newer rustc package (though that would come with the long installation time I'm guessing).

**Comment by samuelcolvin** [comment]
@bellini666 I've tried building with an older version of rust (I had to guess the version as `1.44.1` as it's not included anywhere here), unfortunately the "notify" crate which watchfiles requires also uses `edition = "2021"` so setting it to 2018 in our `Cargo.toml` won't help.

I'll try creating an issue on piwheels asking them to use a newer version of rust and hence fix binaries build, but otherwise I can't really help.

By the way,

> It is a production server in which we cannot use `rustup`.

I'm not sure what you mean here? Rustup is an official way to install rust, and it lets you install rust stable, I don't see why rustup is incompatible with "production"?

**Comment by bellini666** [comment]
> @bellini666 I've tried building with an older version of rust (I had to guess the version as `1.44.1` as it's not included anywhere here), unfortunately the "notify" crate which watchfiles requires also uses `edition = "2021"` so setting it to 2018 in our `Cargo.toml` won't help.
> 
> I'll try creating an issue on piwheels asking them to use a newer version of rust and hence fix binaries build, but otherwise I can't really help.

Sorry for not replying earlier, but happy you were able to reproduce the issue.

And yeah, probably it is something that can be solved at piwheels side.

> 
> By the way,
> 
> > It is a production server in which we cannot use `rustup`.
> 
> I'm not sure what you mean here? Rustup is an official way to install rust, and it lets you install rust stable, I don't see why rustup is incompatible with "production"?

It is more of a "I prefer to use as much as the distro's packages available". Just like I could use `pyenv` at production to use the latest available version of python, I usually prefer to use the distro's one since it is responsible for handling compatibility issues, security updates, etc.

But the major point here is the lack of wheel actually. Being able to build the package is an okish solution, but at the end of the day is not ideal since, as I mentioned earlier, the build time on rpi is too long. I just used a test rpi here, installed the latest rustc with rustup and it took 15 minutes to `pip install whatchfiles` in a venv.

**Comment by samuelcolvin** [comment]
Agreed, see my issue on piwheels linked above.

For your specific case, why not build a binary once and distribute it to all your machines manually as a wheel? Should solve the problem for you until the issue with piwheels is resolved.

**Comment by samuelcolvin** [comment]
@bellini666 and others with a pi, please can you try:

    pip install -i https://pypi.org/simple/ watchfiles==0.15.0a1

and let me know what happens, should now work.

**Comment by bellini666** [comment]
> @bellini666 and others with a pi, please can you try:
> 
> ```
> pip install -i https://pypi.org/simple/ watchfiles==0.15.0a1
> ```
> 
> and let me know what happens, should now work.

@samuelcolvin it installs fine in my rpi with the wheel (without even having to build the rust extension)! :)

Is 0.15 going to be released soon? Looking forward to migrate back from watchgod to watchfiles

**Comment by samuelcolvin** [comment]
Yea, next few days unless something comes up.

**Comment by samuelcolvin** [comment]
v0.15 is released.
